### ISSUE TITLE
Dev Pipeline

### ISSUE THREAD

**Issue by CITguy** [HelixDesignSystem/helix-react#14]
As a developer, I would like to know how to set up my local dev environment, so that I can contribute updates as fast as possible.

-----

- [ ] Netlify should only deploy documentation on merges to `release` branch (not `master`).
- [ ] Linting should run automatically as contributors develop locally
  - all messages should be _warnings_ to the developer
- [ ] Linting should run automatically on PR submit/update
  - any linting issues should immediately fail PR validation

**Comment by CITguy** [comment]
- [ ] Update netlify config to only deploy on merge to `release` branch

**Comment by 100stacks** [comment]
Issue dated.  Tracking work by another method.
