### ISSUE TITLE
Alert

### ISSUE THREAD

**Issue by CITguy** [HelixDesignSystem/helix-react#19]
`<Alert/>` component to wrap `dismiss` and `submit` events from the HelixUI [`<hx-alert>` element](https://helix-ui.netlify.com/elements/hx-alert/).

**Comment by gabecase** [comment]
@CITguy can you assign this to me? Ive got this implemented in our application and would like to contribute it back to helix-react

**Comment by gabecase** [comment]
Starting this back up again now we have time to contribute react components back

**Comment by 100stacks** [comment]
Fixed PR #86.
