### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by CITguy** [HelixDesignSystem/helix-react#21]
`<Menu/>` component to wrap `open` and `close` events from the HelixUI [`<hx-menu>` element](https://helix-ui.netlify.com/elements/hx-menu/).

**Comment by CITguy** [comment]
Should this component encapsulate all types of Helix menus?

* Basic Menu
* Cog Menu
* Grouped Menu
* Split Menu?

https://helix-ui.netlify.com/components/menus/

**Comment by 100stacks** [comment]
Issue dated.  Tracking work by another method.
