### ISSUE TITLE
JSX Removes Necessary Whitespace

### ISSUE THREAD

**Issue by CITguy** [HelixDesignSystem/helix-react#5]
See rackerlabs/helix-ui#283 for details.

# Problem
There are several cases where white space is necessary to apply HelixUI styles to inline elements.
JSX [removes inline whitespace](https://www.bennadel.com/blog/2880-a-quick-look-at-rendering-white-space-using-jsx-in-reactjs.htm) if element nodes are defined on separate physical lines than non-element nodes within JSX source code.

## TL;DR
This JSX template
```javascript
return (
  <button className="hxBtn">
    Text Node
    <hx-icon type="filter"></hx-icon>
  </button>
)
```
renders to
```html
<button class="hxBtn">Text Node<hx-icon type="filter"></hx-icon></button>
```
However, JSX stripped significant whitespace between the text node and the `<hx-icon>` that CSS expects to be present in order to distance the icon properly from the text.

# Solution
When building React components, strategically add white-space-only text nodes into JSX templates using the `{ " " }` syntax.

This JSX template
```javascript
return (
  <button className="hxBtn">
    Text Node
    { " " }
    <hx-icon type="filter"></hx-icon>
  </button>
)
```
renders to
```html
  <button class="hxBtn">Text Node <hx-icon type="filter"></hx-icon></button>
```
This time, JSX inserts the needed white space between the text node and `<hx-icon>` element.

**Comment by 100stacks** [comment]
Issue dated.  Considering updated solution.
