### ISSUE TITLE
Initialize Rollup

### ISSUE THREAD

**Issue by CITguy** [HelixDesignSystem/helix-react#8]
As a Developer, I would like to run a command to generate distributable assets, so that I don't have to build them manually.

-----

* Generate in CommonJS format, for Node consumption.

**Comment by CITguy** [comment]
The typical consumption of HelixReact will be in an environment where the consumer will require a build process (webpack + Babel/TypeScript), which means that consuming code will be . Given this information, we don't actually need rollup, because we can point directly to the source code for consumption.

```javascript
{
  ...
  "main": "src/index.js", /* CJS format */
  "module": "src/index.mjs", /* ESM format */
  ...
}
```

**Comment by cathysiller** [comment]
merged
